---
pull_request_rules:
  - name: Close all on main
    conditions:
      - base=main
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      close:
        message: Please do not open PR's on the `main` branch, but on the `develop`
          branch only. Thank you!
  - name: No translations
    conditions:
      - -author~=^dependabot(|-preview)\[bot\]$
      - base=develop
      - or:
          - files~=^resources/lang/bg_BG
          - files~=^resources/lang/ca_ES
          - files~=^resources/lang/cs_CZ
          - files~=^resources/lang/da_DK
          - files~=^resources/lang/de_DE
          - files~=^resources/lang/el_GR
          - files~=^resources/lang/en_GB
          - files~=^resources/lang/es_ES
          - files~=^resources/lang/et_EE
          - files~=^resources/lang/fa_IR
          - files~=^resources/lang/fi_FI
          - files~=^resources/lang/fr_FR
          - files~=^resources/lang/he_IL
          - files~=^resources/lang/hu_HU
          - files~=^resources/lang/id_ID
          - files~=^resources/lang/is_IS
          - files~=^resources/lang/it_IT
          - files~=^resources/lang/ja_JP
          - files~=^resources/lang/ko_KR
          - files~=^resources/lang/lt_LT
          - files~=^resources/lang/nb_NO
          - files~=^resources/lang/nl_NL
          - files~=^resources/lang/pl_PL
          - files~=^resources/lang/pt_BR
          - files~=^resources/lang/pt_PT
          - files~=^resources/lang/ro_RO
          - files~=^resources/lang/ru_RU
          - files~=^resources/lang/si_LK
          - files~=^resources/lang/sk_SK
          - files~=^resources/lang/sl_SI
          - files~=^resources/lang/sr_CS
          - files~=^resources/lang/sv_SE
          - files~=^resources/lang/th_TH
          - files~=^resources/lang/tlh_AA
          - files~=^resources/lang/tr_TR
          - files~=^resources/lang/uk_UA
          - files~=^resources/lang/vi_VN
          - files~=^resources/lang/zh_CN
          - files~=^resources/lang/zh_TW
    actions:
      comment:
        message: >
          Please do not submit translated strings in your PR. If you need new
          sentences to be translated, add them to the `en_US` language strings.
          New or changed translations for other languages can be submitted at
          https://crowdin.com/project/firefly-iii

          Thank you!
