name: "Issues - Close stale issues"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            Hi there! This is an automatic reply. `Share and enjoy`

            This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

            Thank you for your contributions.
          stale-pr-message: >
            Hi there! This is an automatic reply. `Share and enjoy`

            This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

            Thank you for your contributions.
          days-before-stale: 14
          days-before-close: 7
          exempt-issue-labels: 'enhancement,feature,bug,announcement,epic'
